//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raport_Online
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALAMAT
    {
        public int ID_ALAMAT { get; set; }
        public Nullable<int> ID_WILAYAH { get; set; }
        public Nullable<int> ID_KARYAWAN { get; set; }
        public string DIBUAT_OLEH { get; set; }
        public Nullable<System.DateTime> DIBUAT_PADA { get; set; }
        public string DIUBAH_OLEH { get; set; }
        public System.DateTime DIUBAH_PADA { get; set; }
        public bool STATUS_AKTIF { get; set; }
    
        public virtual KARYAWAN KARYAWAN { get; set; }
        public virtual WILAYAH WILAYAH { get; set; }
    }
}
