//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raport_Online
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_ASPEK
    {
        public int ID_DETAIL { get; set; }
        public Nullable<int> ID_SUB { get; set; }
        public Nullable<int> ID_RAPOR { get; set; }
        public Nullable<int> NILAI_K_A { get; set; }
        public Nullable<int> NILAI_K_B { get; set; }
    
        public virtual RAPOR RAPOR { get; set; }
        public virtual SUB_ASPEK SUB_ASPEK { get; set; }
    }
}
