//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raport_Online
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARYAWAN
    {
        public KARYAWAN()
        {
            this.ALAMAT = new HashSet<ALAMAT>();
            this.DEPARTEMEN = new HashSet<DEPARTEMEN>();
            this.LOGIN = new HashSet<LOGIN>();
            this.RAPOR = new HashSet<RAPOR>();
            this.RAPOR1 = new HashSet<RAPOR>();
        }
    
        public int ID_KARYAWAN { get; set; }
        public Nullable<int> ID_DEPARTEMEN { get; set; }
        public Nullable<int> ID_JABATAN { get; set; }
        public string NO_KTP { get; set; }
        public string NAMA_LENGKAP { get; set; }
        public string JENIS_KELAMIN { get; set; }
        public string TEMPAT_LAHIR { get; set; }
        public System.DateTime TANGGAL_LAHIR { get; set; }
        public string AGAMA { get; set; }
        public string STATUS_PERKAWINAN { get; set; }
        public string KEWARGANEGARAAN { get; set; }
        public string PENDIDIKAN { get; set; }
        public string DIBUAT_OLEH { get; set; }
        public System.DateTime DIBUAT_PADA { get; set; }
        public string DIUBAH_OLEH { get; set; }
        public Nullable<System.DateTime> DIUBAH_PADA { get; set; }
        public bool STATUS_AKTIF { get; set; }
    
        public virtual ICollection<ALAMAT> ALAMAT { get; set; }
        public virtual ICollection<DEPARTEMEN> DEPARTEMEN { get; set; }
        public virtual DEPARTEMEN DEPARTEMEN1 { get; set; }
        public virtual JABATAN JABATAN { get; set; }
        public virtual ICollection<LOGIN> LOGIN { get; set; }
        public virtual ICollection<RAPOR> RAPOR { get; set; }
        public virtual ICollection<RAPOR> RAPOR1 { get; set; }
    }
}
