//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raport_Online
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAPOR
    {
        public RAPOR()
        {
            this.DETAIL_ASPEK = new HashSet<DETAIL_ASPEK>();
        }
    
        public int ID_RAPOR { get; set; }
        public int ID_KARYAWAN { get; set; }
        public int KAR_ID_KARYAWAN { get; set; }
        public int JUMLAH { get; set; }
        public int RATA2 { get; set; }
        public Nullable<bool> BERLAKU { get; set; }
        public Nullable<int> ID_PENILAI { get; set; }
        public Nullable<System.DateTime> PERIODE { get; set; }
        public string DIBUAT_OLEH { get; set; }
        public System.DateTime DIBUAT_PADA { get; set; }
        public string DIUBAH_OLEH { get; set; }
        public Nullable<System.DateTime> DIUBAH_PADA { get; set; }
        public bool STATUS_AKTIF { get; set; }
    
        public virtual ICollection<DETAIL_ASPEK> DETAIL_ASPEK { get; set; }
        public virtual KARYAWAN KARYAWAN { get; set; }
        public virtual KARYAWAN KARYAWAN1 { get; set; }
    }
}
