//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raport_Online
{
    using System;
    using System.Collections.Generic;
    
    public partial class WILAYAH
    {
        public WILAYAH()
        {
            this.ALAMAT = new HashSet<ALAMAT>();
            this.WILAYAH1 = new HashSet<WILAYAH>();
        }
    
        public int ID_WILAYAH { get; set; }
        public Nullable<int> WIL_ID_WILAYAH { get; set; }
        public string NAMA_WIL { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public string DIBUAT_OLEH { get; set; }
        public System.DateTime DIBUAT_PADA { get; set; }
        public string DIUBAH_OLEH { get; set; }
        public Nullable<System.DateTime> DIUBAH_PADA { get; set; }
        public bool STATUS_AKTIF { get; set; }
    
        public virtual ICollection<ALAMAT> ALAMAT { get; set; }
        public virtual ICollection<WILAYAH> WILAYAH1 { get; set; }
        public virtual WILAYAH WILAYAH2 { get; set; }
    }
}
